export const movieDataKey = "movieData"
export const favMovieKey = "favMovie"
export const recentlyWatchedKey = "recentlyWatched"
export const myListKey = "myList"
export const currMovieKey = "currMovie"